version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: idb-keyval
    versions:
    - ">= 5.a, < 6"
  - dependency-name: rollup-plugin-typescript2
    versions:
    - ">= 0.25.a, < 0.26"
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.17
    - 7.12.7
    - 7.13.0
    - 7.13.8
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.17
  - dependency-name: home-assistant-js-websocket
    versions:
    - 5.8.1
  - dependency-name: "@rollup/plugin-typescript"
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.1
    - 11.2.0
  - dependency-name: marked
    versions:
    - 1.2.8
    - 2.0.0
  - dependency-name: "@material/mwc-switch"
    versions:
    - 0.20.0
  - dependency-name: eslint-plugin-lit
    versions:
    - 1.3.0
  - dependency-name: babel-loader
    versions:
    - 8.2.2
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
  - dependency-name: fs-extra
    versions:
    - 9.1.0
  - dependency-name: eslint
    versions:
    - 7.19.0
  - dependency-name: "@material/mwc-list"
    versions:
    - 0.20.0
  - dependency-name: ini
    versions:
    - 1.3.7
    - 1.3.8
  - dependency-name: "@types/resize-observer-browser"
    versions:
    - 0.1.5
  - dependency-name: systemjs
    versions:
    - 6.8.3
  - dependency-name: "@babel/plugin-proposal-decorators"
    versions:
    - 7.12.12
  - dependency-name: highlight.js
    versions:
    - 10.4.1
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: "@rollup/plugin-replace"
    versions:
    - 2.3.4
  - dependency-name: eslint-plugin-react-hooks
    versions:
    - 4.2.0
  - dependency-name: "@webcomponents/webcomponentsjs"
    versions:
    - 2.5.0
