name: "Test build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_frontend:
    name: Test build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Install dependencies
        run: script/bootstrap
      - name: Build
        run: script/build
  bump:
    runs-on: ubuntu-latest
    name: Bump hacs/integration
    steps:
      - name: Initialize git
        uses: home-assistant/actions/helpers/git-init@master
        with:
          name: ${{ secrets.GIT_NAME }}
          email: ${{ secrets.GIT_EMAIL }}
          token: ${{ secrets.GIT_TOKEN }}

      - name: "Set version number"
        id: info
        run: |
          version="20201223162633"
          raw=$(\
              curl -sSL -f "https://github.com/hacs/frontend/releases/tag/${version}" \
              | grep "<li>" \
              | grep "</a></li>" \
              | grep "user" \
              )

          user=$(echo "$raw" | cut -d">" -f 5 | cut -d"<" -f 1)
          change=$(echo "$raw" | cut -d">" -f 2 | cut -d"(" -f 1)
          echo "::set-output name=version::${version}"
          echo "::set-output name=title::$change $user"

      - name: Create PR
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GIT_TOKEN}}
          script: |
            await github.request('POST /repos/{owner}/{repo}/pulls', {
              owner: "hacs",
              repo: "integration",
              title: ${{ steps.info.outputs.title }},
              head: 'frontend/${{ steps.info.outputs.version }}',
              base: 'origin/main'
            })
